images:
- ${_ARTIFACT_REGISTRY}/${_PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}
- ${_ARTIFACT_REGISTRY}/${_PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest
options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: projects/${_PROJECT_ID}/serviceAccounts/${_SERVICE_ACCOUNT}
steps:
- args:
  - build
  - -t
  - ${_ARTIFACT_REGISTRY}/${_PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}
  - -t
  - ${_ARTIFACT_REGISTRY}/${_PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest
  - .
  id: build-image
  name: gcr.io/cloud-builders/docker
- args:
  - push
  - --all-tags
  - ${_ARTIFACT_REGISTRY}/${_PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}
  id: push-image
  name: gcr.io/cloud-builders/docker
  waitFor:
  - build-image
- args:
  - run
  - deploy
  - ${_SERVICE_NAME}
  - --image=${_ARTIFACT_REGISTRY}/${_PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}
  - --region=${_REGION}
  - --platform=managed
  - --allow-unauthenticated
  - --service-account=${_SERVICE_ACCOUNT}
  - --min-instances=${_MIN_INSTANCES}
  - --max-instances=${_MAX_INSTANCES}
  - --cpu=${_CPU}
  - --memory=${_MEMORY}
  - --timeout=${_TIMEOUT}
  - --set-env-vars=PROJECT_ID=${_PROJECT_ID},LOCATION_ID=${_LOCATION_ID},MODEL_ID=${_MODEL_ID},DATASTORE_ID=${_DATASTORE_ID},DATASTORE_LOCATION=${_DATASTORE_LOCATION},DISCOVERY_ENGINE_ID=${_DISCOVERY_ENGINE_ID},DISCOVERY_LOCATION=${_DATASTORE_LOCATION},DISCOVERY_COLLECTION=default_collection,DISCOVERY_SERVING_CONFIG=default_config,SYSTEM_PROMPT_PATH=prompt/prompt.txt,USE_SECRET_MANAGER=True,SERVE_STATIC=false
  entrypoint: gcloud
  id: deploy-service
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  waitFor:
  - push-image
substitutions:
  _ARTIFACT_REGISTRY: asia-northeast3-docker.pkg.dev
  _CPU: '1'
  _DATASTORE_ID: documentation-467305-graphrag-datastore
  _DATASTORE_LOCATION: global
  _DISCOVERY_ENGINE_ID: documentation-467305-graphrag-engine
  _LOCATION_ID: asia-northeast3
  _MAX_INSTANCES: '10'
  _MEMORY: 2Gi
  _MIN_INSTANCES: '0'
  _MODEL_ID: gemini-pro
  _PROJECT_ID: documentation-467305
  _REGION: asia-northeast3
  _REPO_NAME: documentation-467305-graphrag-repo
  _SERVICE_ACCOUNT: graphrag-service@documentation-467305.iam.gserviceaccount.com
  _SERVICE_NAME: documentation-467305-graphrag-api
  _TIMEOUT: 300s
